---
# docker compose -f docker-compose.yml up -d
version: "2.1"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: VerySecretP455w0rd!
      MSSQL_PID: Developer
    ports:
      - 1433:1433
